//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainForm {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Directions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Directions() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainForm.Directions", typeof(Directions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прикладная математика и информатика.
        /// </summary>
        internal static string _01_03_02 {
            get {
                return ResourceManager.GetString("01.03.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Физика.
        /// </summary>
        internal static string _03_03_02 {
            get {
                return ResourceManager.GetString("03.03.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фундаментальная и прикладная химия.
        /// </summary>
        internal static string _04_05_01 {
            get {
                return ResourceManager.GetString("04.05.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Науки о земле (укрупненная группа направлений подготовки).
        /// </summary>
        internal static string _05_03_00 {
            get {
                return ResourceManager.GetString("05.03.00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Биология.
        /// </summary>
        internal static string _06_03_01 {
            get {
                return ResourceManager.GetString("06.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строительство и эксплуатация зданий и сооружений.
        /// </summary>
        internal static string _08_02_01 {
            get {
                return ResourceManager.GetString("08.02.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строительство и эксплуатация автомобильных дорог и аэродромов.
        /// </summary>
        internal static string _08_02_05 {
            get {
                return ResourceManager.GetString("08.02.05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строительство.
        /// </summary>
        internal static string _08_03_01 {
            get {
                return ResourceManager.GetString("08.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строительство уникальных зданий и сооружений.
        /// </summary>
        internal static string _08_05_01 {
            get {
                return ResourceManager.GetString("08.05.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сетевое и системное администрирование.
        /// </summary>
        internal static string _09_02_06 {
            get {
                return ResourceManager.GetString("09.02.06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информационные системы и программирование.
        /// </summary>
        internal static string _09_02_07 {
            get {
                return ResourceManager.GetString("09.02.07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информатика и вычислительная техника (укрупненная группа направлений подготовки).
        /// </summary>
        internal static string _09_03_00 {
            get {
                return ResourceManager.GetString("09.03.00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информатика и вычислительная техника.
        /// </summary>
        internal static string _09_03_01 {
            get {
                return ResourceManager.GetString("09.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информационная безопасность.
        /// </summary>
        internal static string _10_03_01 {
            get {
                return ResourceManager.GetString("10.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Биотехнические системы и технологии.
        /// </summary>
        internal static string _12_03_04 {
            get {
                return ResourceManager.GetString("12.03.04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Техническая эксплуатация и обслуживание электрического и электромеханического оборудования.
        /// </summary>
        internal static string _13_02_11 {
            get {
                return ResourceManager.GetString("13.02.11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Теплоэнергетика и теплотехника.
        /// </summary>
        internal static string _13_03_01 {
            get {
                return ResourceManager.GetString("13.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электроэнергетика и электротехника.
        /// </summary>
        internal static string _13_03_02 {
            get {
                return ResourceManager.GetString("13.03.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ядерные физика и технологии.
        /// </summary>
        internal static string _14_03_02 {
            get {
                return ResourceManager.GetString("14.03.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Монтаж и техническая эксплуатация холодильно-компрессорных машин и установок.
        /// </summary>
        internal static string _15_02_06 {
            get {
                return ResourceManager.GetString("15.02.06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Технология машиностроения.
        /// </summary>
        internal static string _15_02_08 {
            get {
                return ResourceManager.GetString("15.02.08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Машиностроение.
        /// </summary>
        internal static string _15_03_01 {
            get {
                return ResourceManager.GetString("15.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Технологические машины и оборудование.
        /// </summary>
        internal static string _15_03_02 {
            get {
                return ResourceManager.GetString("15.03.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматизация технологических процессов и производств.
        /// </summary>
        internal static string _15_03_04 {
            get {
                return ResourceManager.GetString("15.03.04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конструкторско-технологическое обеспечение машиностроительных производств.
        /// </summary>
        internal static string _15_03_05 {
            get {
                return ResourceManager.GetString("15.03.05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Химическая технология (укрупненная группа направлений подготовки).
        /// </summary>
        internal static string _18_03_00 {
            get {
                return ResourceManager.GetString("18.03.00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Биотехнология.
        /// </summary>
        internal static string _19_03_01 {
            get {
                return ResourceManager.GetString("19.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Техносферная безопасность.
        /// </summary>
        internal static string _20_03_01 {
            get {
                return ResourceManager.GetString("20.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нефтегазовое дело.
        /// </summary>
        internal static string _21_03_01 {
            get {
                return ResourceManager.GetString("21.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Землеустройство и кадастры.
        /// </summary>
        internal static string _21_03_02 {
            get {
                return ResourceManager.GetString("21.03.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прикладная геология.
        /// </summary>
        internal static string _21_05_02 {
            get {
                return ResourceManager.GetString("21.05.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Горное дело.
        /// </summary>
        internal static string _21_05_04 {
            get {
                return ResourceManager.GetString("21.05.04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сварочное производство.
        /// </summary>
        internal static string _22_02_06 {
            get {
                return ResourceManager.GetString("22.02.06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Организация перевозок и управления на транспорте.
        /// </summary>
        internal static string _23_02_01 {
            get {
                return ResourceManager.GetString("23.02.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Техническая эксплуатация подъёмно-транспортных, строительных, дорожных машин и оборудования.
        /// </summary>
        internal static string _23_02_04 {
            get {
                return ResourceManager.GetString("23.02.04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Техническое обслуживание, ремонт двигателей, систем и агрегатов автомобилей.
        /// </summary>
        internal static string _23_02_07 {
            get {
                return ResourceManager.GetString("23.02.07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наземные транспортно-технологические средства.
        /// </summary>
        internal static string _23_05_01 {
            get {
                return ResourceManager.GetString("23.05.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Судостроение.
        /// </summary>
        internal static string _26_02_02 {
            get {
                return ResourceManager.GetString("26.02.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Судовождение.
        /// </summary>
        internal static string _26_02_03 {
            get {
                return ResourceManager.GetString("26.02.03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Монтаж и техническое обслуживание судовых машин и механизмов.
        /// </summary>
        internal static string _26_02_04 {
            get {
                return ResourceManager.GetString("26.02.04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эксплуатация судовых энергетических установок.
        /// </summary>
        internal static string _26_02_05 {
            get {
                return ResourceManager.GetString("26.02.05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эксплуатация судового электрооборудования и средств автоматики.
        /// </summary>
        internal static string _26_02_06 {
            get {
                return ResourceManager.GetString("26.02.06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кораблестроение, океанотехника и системотехника объектов морской инфраструктуры.
        /// </summary>
        internal static string _26_03_02 {
            get {
                return ResourceManager.GetString("26.03.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проектирование и постройка кораблей, судов и объектов океанотехники.
        /// </summary>
        internal static string _26_05_01 {
            get {
                return ResourceManager.GetString("26.05.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проектирование, изготовление и ремонт энергетических установок и систем автоматизации кораблей и судов.
        /// </summary>
        internal static string _26_05_02 {
            get {
                return ResourceManager.GetString("26.05.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стандартизация и метрология.
        /// </summary>
        internal static string _27_03_01 {
            get {
                return ResourceManager.GetString("27.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление в технических системах.
        /// </summary>
        internal static string _27_03_04 {
            get {
                return ResourceManager.GetString("27.03.04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нанотехнологии и микросистемная техника.
        /// </summary>
        internal static string _28_03_01 {
            get {
                return ResourceManager.GetString("28.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лесное и лесопарковое хозяйство.
        /// </summary>
        internal static string _35_02_01 {
            get {
                return ResourceManager.GetString("35.02.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обработка водных биоресурсов.
        /// </summary>
        internal static string _35_02_10 {
            get {
                return ResourceManager.GetString("35.02.10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лесное дело.
        /// </summary>
        internal static string _35_03_01 {
            get {
                return ResourceManager.GetString("35.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Технология лесозаготовительных и деревоперерабатывающих производств.
        /// </summary>
        internal static string _35_03_02 {
            get {
                return ResourceManager.GetString("35.03.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ландшафтная архитектура.
        /// </summary>
        internal static string _35_03_10 {
            get {
                return ResourceManager.GetString("35.03.10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Психология.
        /// </summary>
        internal static string _37_03_01 {
            get {
                return ResourceManager.GetString("37.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Психология служебной деятельности.
        /// </summary>
        internal static string _37_05_02 {
            get {
                return ResourceManager.GetString("37.05.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экономика.
        /// </summary>
        internal static string _38_03_01 {
            get {
                return ResourceManager.GetString("38.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менеджмент.
        /// </summary>
        internal static string _38_03_02 {
            get {
                return ResourceManager.GetString("38.03.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Государственное и муниципальное управление.
        /// </summary>
        internal static string _38_03_04 {
            get {
                return ResourceManager.GetString("38.03.04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бизнес-информатика.
        /// </summary>
        internal static string _38_03_05 {
            get {
                return ResourceManager.GetString("38.03.05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Социология.
        /// </summary>
        internal static string _39_03_01 {
            get {
                return ResourceManager.GetString("39.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Социальная работа.
        /// </summary>
        internal static string _39_03_02 {
            get {
                return ResourceManager.GetString("39.03.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Организация работы с молодёжью.
        /// </summary>
        internal static string _39_03_03 {
            get {
                return ResourceManager.GetString("39.03.03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Юриспруденция.
        /// </summary>
        internal static string _40_03_01 {
            get {
                return ResourceManager.GetString("40.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регионоведение России.
        /// </summary>
        internal static string _41_03_02 {
            get {
                return ResourceManager.GetString("41.03.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Международные отношения.
        /// </summary>
        internal static string _41_03_05 {
            get {
                return ResourceManager.GetString("41.03.05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Публичная политика и социальные науки.
        /// </summary>
        internal static string _41_03_06 {
            get {
                return ResourceManager.GetString("41.03.06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реклама и связи с общественностью.
        /// </summary>
        internal static string _42_03_01 {
            get {
                return ResourceManager.GetString("42.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Журналистика.
        /// </summary>
        internal static string _42_03_02 {
            get {
                return ResourceManager.GetString("42.03.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Туризм.
        /// </summary>
        internal static string _43_03_02 {
            get {
                return ResourceManager.GetString("43.03.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Педагогическое образование.
        /// </summary>
        internal static string _44_03_01 {
            get {
                return ResourceManager.GetString("44.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Психолого-педагогическое образование.
        /// </summary>
        internal static string _44_03_02 {
            get {
                return ResourceManager.GetString("44.03.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Специальное (дефектологическое) образование.
        /// </summary>
        internal static string _44_03_03 {
            get {
                return ResourceManager.GetString("44.03.03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Педагогическое образование (с двумя профилями подготовки).
        /// </summary>
        internal static string _44_03_05 {
            get {
                return ResourceManager.GetString("44.03.05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Педагогика и психология девиантного поведения.
        /// </summary>
        internal static string _44_05_01 {
            get {
                return ResourceManager.GetString("44.05.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Филология.
        /// </summary>
        internal static string _45_03_01 {
            get {
                return ResourceManager.GetString("45.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лингвистика.
        /// </summary>
        internal static string _45_03_02 {
            get {
                return ResourceManager.GetString("45.03.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История.
        /// </summary>
        internal static string _46_03_01 {
            get {
                return ResourceManager.GetString("46.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Религиоведение.
        /// </summary>
        internal static string _47_03_03 {
            get {
                return ResourceManager.GetString("47.03.03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Физическая культура.
        /// </summary>
        internal static string _49_03_01 {
            get {
                return ResourceManager.GetString("49.03.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Физическая культура для лиц с отклонениями в состоянии здоровья.
        /// </summary>
        internal static string _49_03_02 {
            get {
                return ResourceManager.GetString("49.03.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Культурология.
        /// </summary>
        internal static string _51_03_01 {
            get {
                return ResourceManager.GetString("51.03.01", resourceCulture);
            }
        }
    }
}
