//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratorV2.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonData() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneratorV2.Properties.CommonData", typeof(CommonData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на / Высшая школа /.
        /// </summary>
        internal static string @__hs {
            get {
                return ResourceManager.GetString("__hs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Министерство науки и высшего образования Российской Федерации.
        /// </summary>
        internal static string @__ministry {
            get {
                return ResourceManager.GetString("__ministry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Руководитель.
        /// </summary>
        internal static string @__sto_advA {
            get {
                return ResourceManager.GetString("__sto_advA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (подпись руководителя).
        /// </summary>
        internal static string @__sto_advB {
            get {
                return ResourceManager.GetString("__sto_advB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (инициалы, фамилия).
        /// </summary>
        internal static string @__sto_advC {
            get {
                return ResourceManager.GetString("__sto_advC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курс:.
        /// </summary>
        internal static string @__sto_course {
            get {
                return ResourceManager.GetString("__sto_course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (дата).
        /// </summary>
        internal static string @__sto_date {
            get {
                return ResourceManager.GetString("__sto_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Направление подготовки / специальность:.
        /// </summary>
        internal static string @__sto_dirA {
            get {
                return ResourceManager.GetString("__sto_dirA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (код и наименование).
        /// </summary>
        internal static string @__sto_dirB {
            get {
                return ResourceManager.GetString("__sto_dirB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По дисциплине.
        /// </summary>
        internal static string @__sto_discA {
            get {
                return ResourceManager.GetString("__sto_discA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По междисциплинарному курсу.
        /// </summary>
        internal static string @__sto_discB {
            get {
                return ResourceManager.GetString("__sto_discB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По модулю.
        /// </summary>
        internal static string @__sto_discC {
            get {
                return ResourceManager.GetString("__sto_discC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнила обучающаяся:.
        /// </summary>
        internal static string @__sto_execF {
            get {
                return ResourceManager.GetString("__sto_execF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнил обучающийся:.
        /// </summary>
        internal static string @__sto_execM {
            get {
                return ResourceManager.GetString("__sto_execM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группа:.
        /// </summary>
        internal static string @__sto_group {
            get {
                return ResourceManager.GetString("__sto_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (наименование высшей школы / филиала / института / колледжа).
        /// </summary>
        internal static string @__sto_hs {
            get {
                return ResourceManager.GetString("__sto_hs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отметка о зачёте.
        /// </summary>
        internal static string @__sto_markA {
            get {
                return ResourceManager.GetString("__sto_markA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (отметка прописью).
        /// </summary>
        internal static string @__sto_markB {
            get {
                return ResourceManager.GetString("__sto_markB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Ф.И.О. руководителя, должность / уч. степень / звание).
        /// </summary>
        internal static string @__sto_prepod {
            get {
                return ResourceManager.GetString("__sto_prepod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Ф.И.О.).
        /// </summary>
        internal static string @__sto_stud {
            get {
                return ResourceManager.GetString("__sto_stud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На тему.
        /// </summary>
        internal static string @__sto_theme {
            get {
                return ResourceManager.GetString("__sto_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на федеральное государственное автономное образовательное учреждение.
        /// </summary>
        internal static string @__universityA {
            get {
                return ResourceManager.GetString("__universityA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на высшего образования.
        /// </summary>
        internal static string @__universityB {
            get {
                return ResourceManager.GetString("__universityB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на «Северный (Арктический) федеральный университет имени М.В. Ломоносова».
        /// </summary>
        internal static string @__universityC {
            get {
                return ResourceManager.GetString("__universityC", resourceCulture);
            }
        }
    }
}
